services:
  db:
    container_name: test-application-database
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: app
    ports:
     - "5432:5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data



volumes:
  postgres_data: {}